import type { Metadata } from "next";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { Suspense } from "react";
import ClientProviders from "@/components/providers/ClientProviders";
import ConditionalLayout from "@/components/layout/ConditionalLayout";

interface LayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function LayoutContent({
  children,
  locale,
}: {
  children: React.ReactNode;
  locale: string;
}) {
  return (
    <body
      className="font-sans min-h-screen bg-background text-foreground antialiased selection:bg-primary selection:text-primary-foreground"
      suppressHydrationWarning
    >
      <Suspense
        fallback={
          <div className="min-h-screen bg-background flex items-center justify-center">
            <div className="flex flex-col items-center space-y-4">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
              <p className="text-sm text-muted-foreground">Loading...</p>
            </div>
          </div>
        }
      >
        <NextIntlClientProvider locale={locale}>
          <ClientProviders>
            <ConditionalLayout>{children}</ConditionalLayout>
          </ClientProviders>
        </NextIntlClientProvider>
      </Suspense>
    </body>
  );
}

export default async function LocaleLayout({ children, params }: LayoutProps) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html
      lang={locale}
      suppressHydrationWarning
      className="scroll-smooth relative"
    >
      <Suspense
        fallback={
          <body className="min-h-screen bg-background">
            <div className="min-h-screen bg-background flex items-center justify-center">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary" />
            </div>
          </body>
        }
      >
        <LayoutContent locale={locale}>{children}</LayoutContent>
      </Suspense>
    </html>
  );
}
